name: Cypress Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  cypress-run:
    runs-on: ubuntu-24.04

    container:
      image: cypress/browsers:node-22.15.0-chrome-136.0.7103.92-1-ff-138.0.1-edge-136.0.3240.50-1

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          browser: chrome
          record: true
          parallel: true
          group: UI - Production
        env:
          CYPRESS_BASE_URL: https://adopet-tau.vercel.app
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}